import type { Resource } from "../constitution/schema.js";

const HEADER = `// Generated by Republic - DO NOT EDIT
// Regenerate with: republic build
`;

export function generateHandler(resource: Resource): string {
  const name = resource.name;
  const lowerName = name.toLowerCase();
  const lines: string[] = [HEADER];

  lines.push(`import type { Request, Response } from "express";`);
  lines.push(`import type { ${name}, Create${name}Input } from "../models/${name}.js";`);
  lines.push("");

  // In-memory store for PoC
  lines.push(`// In-memory store (replace with database in production)`);
  lines.push(`const ${lowerName}s: Map<string, ${name}> = new Map();`);
  lines.push("");

  // Generate handlers based on operations
  if (resource.operations.includes("list")) {
    lines.push(`export function list${name}s(_req: Request, res: Response): void {`);
    lines.push(`  const items = Array.from(${lowerName}s.values());`);
    lines.push(`  res.json(items);`);
    lines.push(`}`);
    lines.push("");
  }

  if (resource.operations.includes("get")) {
    lines.push(`export function get${name}(req: Request, res: Response): void {`);
    lines.push(`  const { id } = req.params;`);
    lines.push(`  const item = ${lowerName}s.get(id);`);
    lines.push(`  if (!item) {`);
    lines.push(`    res.status(404).json({ error: "${name} not found" });`);
    lines.push(`    return;`);
    lines.push(`  }`);
    lines.push(`  res.json(item);`);
    lines.push(`}`);
    lines.push("");
  }

  if (resource.operations.includes("create")) {
    lines.push(`export function create${name}(req: Request, res: Response): void {`);
    lines.push(`  const input: Create${name}Input = req.body;`);
    lines.push(`  const id = crypto.randomUUID();`);
    lines.push(`  const item: ${name} = { id, ...input };`);
    lines.push(`  ${lowerName}s.set(id, item);`);
    lines.push(`  res.status(201).json(item);`);
    lines.push(`}`);
    lines.push("");
  }

  if (resource.operations.includes("update")) {
    lines.push(`export function update${name}(req: Request, res: Response): void {`);
    lines.push(`  const { id } = req.params;`);
    lines.push(`  const existing = ${lowerName}s.get(id);`);
    lines.push(`  if (!existing) {`);
    lines.push(`    res.status(404).json({ error: "${name} not found" });`);
    lines.push(`    return;`);
    lines.push(`  }`);
    lines.push(`  const updated: ${name} = { ...existing, ...req.body, id };`);
    lines.push(`  ${lowerName}s.set(id, updated);`);
    lines.push(`  res.json(updated);`);
    lines.push(`}`);
    lines.push("");
  }

  if (resource.operations.includes("delete")) {
    lines.push(`export function delete${name}(req: Request, res: Response): void {`);
    lines.push(`  const { id } = req.params;`);
    lines.push(`  if (!${lowerName}s.has(id)) {`);
    lines.push(`    res.status(404).json({ error: "${name} not found" });`);
    lines.push(`    return;`);
    lines.push(`  }`);
    lines.push(`  ${lowerName}s.delete(id);`);
    lines.push(`  res.status(204).send();`);
    lines.push(`}`);
    lines.push("");
  }

  return lines.join("\n");
}
