import type { Resource, FieldType } from "../constitution/schema.js";

const HEADER = `// Generated by Republic - DO NOT EDIT
// Regenerate with: republic build
`;

function mapType(fieldType: FieldType): string {
  switch (fieldType) {
    case "string":
      return "string";
    case "number":
      return "number";
    case "boolean":
      return "boolean";
    case "date":
      return "Date";
  }
}

export function generateModel(resource: Resource): string {
  const lines: string[] = [HEADER];

  lines.push(`export interface ${resource.name} {`);
  for (const field of resource.fields) {
    const optional = field.required ? "" : "?";
    lines.push(`  ${field.name}${optional}: ${mapType(field.type)};`);
  }
  lines.push("}");
  lines.push("");

  // Generate create input type (without id)
  lines.push(`export interface Create${resource.name}Input {`);
  for (const field of resource.fields) {
    if (field.name === "id") continue;
    const optional = field.required ? "" : "?";
    lines.push(`  ${field.name}${optional}: ${mapType(field.type)};`);
  }
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}
