import type { Resource } from "../constitution/schema.js";

const HEADER = `// Generated by Republic - DO NOT EDIT
// Regenerate with: republic build
`;

export function generateRouter(resources: Resource[]): string {
  const lines: string[] = [HEADER];

  lines.push(`import { Router } from "express";`);

  // Import handlers for each resource
  for (const resource of resources) {
    const name = resource.name;
    const handlers: string[] = [];
    if (resource.operations.includes("list")) handlers.push(`list${name}s`);
    if (resource.operations.includes("get")) handlers.push(`get${name}`);
    if (resource.operations.includes("create")) handlers.push(`create${name}`);
    if (resource.operations.includes("update")) handlers.push(`update${name}`);
    if (resource.operations.includes("delete")) handlers.push(`delete${name}`);
    lines.push(`import { ${handlers.join(", ")} } from "./handlers/${name}Handler.js";`);
  }
  lines.push("");

  lines.push(`export const router = Router();`);
  lines.push("");

  // Generate routes for each resource
  for (const resource of resources) {
    const name = resource.name;
    const path = `/${name.toLowerCase()}s`;

    lines.push(`// ${name} routes`);
    if (resource.operations.includes("list")) {
      lines.push(`router.get("${path}", list${name}s);`);
    }
    if (resource.operations.includes("get")) {
      lines.push(`router.get("${path}/:id", get${name});`);
    }
    if (resource.operations.includes("create")) {
      lines.push(`router.post("${path}", create${name});`);
    }
    if (resource.operations.includes("update")) {
      lines.push(`router.put("${path}/:id", update${name});`);
    }
    if (resource.operations.includes("delete")) {
      lines.push(`router.delete("${path}/:id", delete${name});`);
    }
    lines.push("");
  }

  return lines.join("\n");
}
