import type { Resource } from "../constitution/schema.js";

const HEADER = `// Generated by Republic - DO NOT EDIT
// Regenerate with: republic build
`;

export function generateTests(resource: Resource): string {
  const name = resource.name;
  const lines: string[] = [HEADER];

  lines.push(`import { describe, it, expect } from "vitest";`);
  lines.push(`import type { ${name}, Create${name}Input } from "../models/${name}.js";`);
  lines.push("");

  lines.push(`describe("${name}", () => {`);

  // Type validation tests
  lines.push(`  describe("type validation", () => {`);
  lines.push(`    it("should have required fields", () => {`);
  lines.push(`      const item: ${name} = {`);
  for (const field of resource.fields) {
    const value = getDefaultValue(field.type);
    lines.push(`        ${field.name}: ${value},`);
  }
  lines.push(`      };`);
  lines.push(`      expect(item).toBeDefined();`);
  for (const field of resource.fields) {
    lines.push(`      expect(item.${field.name}).toBeDefined();`);
  }
  lines.push(`    });`);
  lines.push(`  });`);

  // Create input tests
  if (resource.operations.includes("create")) {
    lines.push("");
    lines.push(`  describe("Create${name}Input", () => {`);
    lines.push(`    it("should not require id field", () => {`);
    lines.push(`      const input: Create${name}Input = {`);
    for (const field of resource.fields) {
      if (field.name === "id") continue;
      const value = getDefaultValue(field.type);
      lines.push(`        ${field.name}: ${value},`);
    }
    lines.push(`      };`);
    lines.push(`      expect(input).toBeDefined();`);
    lines.push(`    });`);
    lines.push(`  });`);
  }

  lines.push(`});`);
  lines.push("");

  return lines.join("\n");
}

function getDefaultValue(type: string): string {
  switch (type) {
    case "string":
      return '"test"';
    case "number":
      return "1";
    case "boolean":
      return "true";
    case "date":
      return "new Date()";
    default:
      return '""';
  }
}
