import { describe, it, expect } from "vitest";
import {
  version,
  parseConstitution,
  createDefaultConstitution,
  generateModel,
  generateHandler,
  generateRouter,
  generateTests,
} from "./index";

describe("version", () => {
  it("should return the version string", () => {
    expect(version()).toBe("0.0.1");
  });
});

describe("parseConstitution", () => {
  it("should parse valid constitution", () => {
    const json = JSON.stringify({
      version: "0.1.0",
      name: "test-app",
      resources: [
        {
          name: "Post",
          fields: [{ name: "id", type: "string" }],
          operations: ["list"],
        },
      ],
    });

    const result = parseConstitution(json);
    expect(result.success).toBe(true);
    if (result.success) {
      expect(result.data.name).toBe("test-app");
      expect(result.data.resources).toHaveLength(1);
    }
  });

  it("should reject invalid JSON", () => {
    const result = parseConstitution("not json");
    expect(result.success).toBe(false);
    if (!result.success) {
      expect(result.errors).toContain("Invalid JSON");
    }
  });

  it("should reject invalid resource name", () => {
    const json = JSON.stringify({
      version: "0.1.0",
      name: "test-app",
      resources: [
        {
          name: "post", // should be PascalCase
          fields: [{ name: "id", type: "string" }],
          operations: ["list"],
        },
      ],
    });

    const result = parseConstitution(json);
    expect(result.success).toBe(false);
  });
});

describe("createDefaultConstitution", () => {
  it("should create constitution with given name", () => {
    const constitution = createDefaultConstitution("my-app");
    expect(constitution.name).toBe("my-app");
    expect(constitution.resources).toHaveLength(1);
    expect(constitution.resources[0].name).toBe("Post");
  });
});

describe("generateModel", () => {
  it("should generate TypeScript interface", () => {
    const resource = {
      name: "Post",
      fields: [
        { name: "id", type: "string" as const, required: true },
        { name: "title", type: "string" as const, required: true },
      ],
      operations: ["list" as const],
    };

    const code = generateModel(resource);
    expect(code).toContain("export interface Post");
    expect(code).toContain("id: string");
    expect(code).toContain("title: string");
    expect(code).toContain("Generated by Republic");
  });
});

describe("generateHandler", () => {
  it("should generate handlers for operations", () => {
    const resource = {
      name: "Post",
      fields: [{ name: "id", type: "string" as const, required: true }],
      operations: ["list" as const, "get" as const, "create" as const],
    };

    const code = generateHandler(resource);
    expect(code).toContain("export function listPosts");
    expect(code).toContain("export function getPost");
    expect(code).toContain("export function createPost");
  });
});

describe("generateRouter", () => {
  it("should generate Express router", () => {
    const resources = [
      {
        name: "Post",
        fields: [{ name: "id", type: "string" as const, required: true }],
        operations: ["list" as const, "get" as const],
      },
    ];

    const code = generateRouter(resources);
    expect(code).toContain('import { Router } from "express"');
    expect(code).toContain('router.get("/posts"');
    expect(code).toContain('router.get("/posts/:id"');
  });
});

describe("generateTests", () => {
  it("should generate test file", () => {
    const resource = {
      name: "Post",
      fields: [
        { name: "id", type: "string" as const, required: true },
        { name: "title", type: "string" as const, required: true },
      ],
      operations: ["create" as const],
    };

    const code = generateTests(resource);
    expect(code).toContain('describe("Post"');
    expect(code).toContain("expect(item).toBeDefined()");
    expect(code).toContain("CreatePostInput");
  });
});

describe("determinism", () => {
  it("should generate identical output for same input", () => {
    const resource = {
      name: "Post",
      fields: [
        { name: "id", type: "string" as const, required: true },
        { name: "title", type: "string" as const, required: true },
      ],
      operations: ["list" as const, "get" as const],
    };

    const model1 = generateModel(resource);
    const model2 = generateModel(resource);
    expect(model1).toBe(model2);

    const handler1 = generateHandler(resource);
    const handler2 = generateHandler(resource);
    expect(handler1).toBe(handler2);
  });
});
